language: node_js
os: linux
dist: focal
node_js: 16

cache:
  npm: false
  directories:
    - $HOME/.yarn/berry/cache

git:
  # required to enable symlinks on windows
  symlinks: true

install:
  - yarn && yarn run build
script: yarn run ci

jobs:
  include:
    - node_js: 18
      script: # also run lint on node 18
        - yarn run lint
        - yarn run ci

    - node_js: 16
    - node_js: 14

    - os: windows
      node_js: 18
      env:
        - YARN_GPG=no
      script: yarn test

    - stage: cypress
      script: yarn ci:cypress
      name: Cypress 1
      env: [STAGE_NAME="4x Cypress"]

    - stage: cypress
      script: yarn ci:cypress
      name: Cypress 2
      env: [STAGE_NAME="4x Cypress"]

    - stage: cypress
      script: yarn ci:cypress
      name: Cypress 3
      env: [STAGE_NAME="4x Cypress"]

    - stage: cypress
      script: yarn ci:cypress
      name: Cypress 4
      env: [STAGE_NAME="4x Cypress"]

    - stage: deploy
      if: branch != main
      script: yarn run chromatic

    - stage: deploy
      if: branch = main
      script: |
        yarn run chromatic --auto-accept-changes \
        && yarn run build-native \
        && yarn run semantic-release
