language: node_js
os: linux
dist: focal
node_js: 16

cache:
  npm: false
  directories:
  - $HOME/.yarn/berry/cache

git:
  # required to enable symlinks on windows
  symlinks: true

install:
  - yarn && yarn run build
script: yarn run ci

jobs:
  include:
    - node_js: 18
      script:  # also run lint on node 18
      - yarn run lint
      - yarn run ci

    - node_js: 16
    - node_js: 14

    - os: windows
      node_js: 18
      env:
        - YARN_GPG=no
      before_install:
        # else posix@npm:4.2.0 uses python 2.7.9 to install itself and
        # errors out saying it needs python >=3.6.0
        - choco install python3
      install:
        # refreshenv picks up the new PATH vars set by choco installing python3
        - powershell -Command "refreshenv; yarn; yarn run build"
      script: yarn test

    - stage: deploy
      if: branch != main
      script: yarn run chromatic

    - stage: deploy
      if: branch = main
      script: |
        yarn run chromatic --auto-accept-changes \
        && yarn run build-native \
        && yarn run semantic-release
