name: CI

# TODO: Change to pull_request
on: [push]

permissions:
  contents: read

env:
  APPMAP_TELEMETRY_DISABLED: 'true'

jobs:
  yarn_install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Look up if node_module cache exist
        id: cache
        uses: actions/cache/restore@v3
        with:
          lookup-only: true
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-
        if: steps.cache.outputs.cache-hit != 'true'
      - uses: actions/setup-node@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --immutable
        if: steps.cache.outputs.cache-hit != 'true'

  test:
    runs-on: ubuntu-latest

    needs: [yarn_install]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Restore node_modules
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install AppMap tools
        run: |
          curl -o /usr/local/bin/appmap -L https://github.com/getappmap/appmap-js/releases/download/%40appland%2Fappmap-preflight-v1.0-pre.26/appmap-preflight-linux-x64
          chmod a+x /usr/local/bin/appmap

      - name: Build
        id: build
        run: |
          cd packages/models
          yarn build

      - name: Test
        id: test
        run: |
          set +e
          cd packages/models
          # TODO: Try and fix error
          # APPMAP-ERROR Could not resolve jest preset at "ts-jest/presets/js-with-ts"
          yarn install
          yarn test
          exit_status=$?
          echo "exit-status=$exit_status" >> $GITHUB_OUTPUT

      - name: Create AppMap archive
        uses: getappmap/archive-appmap-action@v1-pre.13

      - name: Report the exit status
        if: steps.test.outputs.exit-status != 0
        run: exit ${{ steps.test.outputs.exit-status }}
